//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_type_image
    {
        public int item_type_image_id { get; set; }
        public int item_type_image_type_id { get; set; }
        public byte[] item_type_image_picture { get; set; }
    
        public virtual item_type item_type { get; set; }
    }
}
