//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaciton
    {
        public int transaction_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public int transaction_system_user_id { get; set; }
        public int transaction_other_user_id { get; set; }
        public int transaction_type_id { get; set; }
        public string transaction_remarks { get; set; }
        public Nullable<int> transaction_item_id { get; set; }
        public Nullable<int> transaction_request_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
