//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_brand_summary
    {
        public int BrandId { get; set; }
        public Nullable<int> ItemSubTypeId { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> ItemCount { get; set; }
    }
}
