//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_item_schedule_summary
    {
        public int request_id { get; set; }
        public Nullable<System.DateTime> request_need_date { get; set; }
        public Nullable<System.DateTime> request_expected_return_date { get; set; }
        public Nullable<int> request_item_id { get; set; }
    }
}
