//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_item_log
    {
        public int TransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionTypeId { get; set; }
        public string SystemFirstname { get; set; }
        public string SystemLastname { get; set; }
        public string OtherUserFirstname { get; set; }
        public string OtherUserLastname { get; set; }
        public Nullable<int> OtherUserId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemId { get; set; }
    }
}
