//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_item_type_summary
    {
        public int ITTypeId { get; set; }
        public string ITTypeName { get; set; }
        public Nullable<int> ITTotalAvailable { get; set; }
        public byte[] Picture { get; set; }
    }
}
