//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_item_subtype_count
    {
        public int SubTypeId { get; set; }
        public string SubTypeName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SubTypeItemCount { get; set; }
        public byte[] Picture { get; set; }
    }
}
