//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_transmittal_details
    {
        public int TransmittalId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Receiver { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public string PreparedBy { get; set; }
        public string ApprovedBy { get; set; }
    }
}
