//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_transmittal_items_details
    {
        public int TransmittalId { get; set; }
        public string ItemName { get; set; }
        public string AssetTag { get; set; }
        public string ItemType { get; set; }
        public string ItemSubType { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int TransmittalItemId { get; set; }
    }
}
