//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLib.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_membership_detail
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int UserTyp { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public Nullable<int> UserDeparmentId { get; set; }
        public string UserDepartment { get; set; }
        public Nullable<int> UserCompanyId { get; set; }
        public string UserCompany { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> UserIsMale { get; set; }
    }
}
