//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string asset_tag { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int item_type { get; set; }
        public int item_sub_type { get; set; }
        public decimal purchase_price { get; set; }
        public decimal current_value { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> life_span { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_user { get; set; }
        public Nullable<int> brand_id { get; set; }
        public string model { get; set; }
        public string serial { get; set; }
        public Nullable<int> current_owner { get; set; }
        public Nullable<int> os_id { get; set; }
        public Nullable<int> processor_id { get; set; }
        public Nullable<int> memory_id { get; set; }
        public Nullable<int> hdd1_id { get; set; }
        public Nullable<int> hdd2_id { get; set; }
    }
}
