//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int request_id { get; set; }
        public int request_user_id { get; set; }
        public int request_type { get; set; }
        public int request_item_primary_type { get; set; }
        public int request_item_secondary_type { get; set; }
        public string request_subtype { get; set; }
        public System.DateTime request_date { get; set; }
        public Nullable<System.DateTime> request_process_date { get; set; }
        public int request_status { get; set; }
        public int request_requested_by_id { get; set; }
        public Nullable<int> request_process_by_id { get; set; }
        public string request_remarks { get; set; }
        public Nullable<System.DateTime> request_need_date { get; set; }
        public Nullable<System.DateTime> request_expected_return_date { get; set; }
        public string request_admin_remarks { get; set; }
        public Nullable<int> request_item_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
