//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.requests = new HashSet<request>();
            this.transacitons = new HashSet<transaciton>();
        }
    
        public int user_id { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
        public int user_type { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public Nullable<int> user_department { get; set; }
        public Nullable<int> user_company { get; set; }
    
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request> requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaciton> transacitons { get; set; }
    }
}
