//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_transaction_summary
    {
        public int TransactionId { get; set; }
        public System.DateTime TranscationDate { get; set; }
        public string SystemUser { get; set; }
        public string CustomerUser { get; set; }
        public string TransactionType { get; set; }
        public string ItemName { get; set; }
        public int SystemUserId { get; set; }
        public int CustomerUserId { get; set; }
        public int TransactionTypeId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Remarks { get; set; }
    }
}
