//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemDetail
    {
        public int id { get; set; }
        public string AssetTag { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemSubTypeId { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal CurrentValue { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> LifeSpan { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedUser { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string model { get; set; }
        public string serial { get; set; }
        public Nullable<int> CurrentOwner { get; set; }
        public Nullable<int> OsId { get; set; }
        public Nullable<int> ProcessorId { get; set; }
        public Nullable<int> MemoryId { get; set; }
        public Nullable<int> HddId { get; set; }
        public Nullable<int> Hdd2Id { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public string TypeName { get; set; }
        public string SubTypeName { get; set; }
        public string BrandName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string Username { get; set; }
    }
}
