//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemDepeciationReport
    {
        public string type { get; set; }
        public string subtype { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string asset_tag { get; set; }
        public int item_type_id { get; set; }
        public int item_sub_type_id { get; set; }
        public decimal purchase_price { get; set; }
        public decimal current_value { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> life_span { get; set; }
        public Nullable<decimal> salvage_value { get; set; }
        public int id { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
    }
}
