//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemSubTypeSummary
    {
        public string ISTType { get; set; }
        public string ISTSubType { get; set; }
        public Nullable<int> ISTTotalAvailable { get; set; }
        public Nullable<int> ISTTypeId { get; set; }
        public int ISTSubTypeID { get; set; }
    }
}
